name = "order-2025-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "order_2025_db"
database_name = "order-2025-db"
database_id = "d127c2ea-f921-415d-935b-32c7adaaf83f"

[build]
command = "echo 'Build completed'"
